server:
  port: 8890
  baseurl: https://chenzequn.mynatapp.cc/
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 16KB
  servlet:
    context-path: /woc-web-admin

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5






